### ISSUE TITLE
Componentes a serem criados 2

### ISSUE THREAD

**Issue by eglauko** [Royal-Code/Yasamen#8]
Outra série de componentes que podem ser criados, adicionais aos da primeira listagem.

Não é necessário que os da primeira lista sejam criados primeiro, mas eles podem ser intercalados conforme a necessidade.

Componentes gerais:

- [ ] Drag & Drop (deve ter uma área e item, onde eles se repetem e os itens podem ser movidos entre as áreas).
- [ ] VideoPlayer
- [ ] Camera
- [ ] Speech
- [ ] Split (um painel com uma linha divisória que pode ser movida)
- [ ] GoTop (botão para mover o scroll para o topo [fixo na tela ou incorporado no documento])
- [ ] RibbonTab (tipo do word, várias abas, sessões e botões com um ícone grande e uma descrição)
- [ ] IpAddressField
- [ ] Captcha (Quebra cabeça tipo binance)
- [ ] ProgressCircle
- [ ] Geolocation (busca as coordenadas)
- [ ] SearchField (Campo/componente de busca/pesquisa, utilizado no topbar [Exibir atalho com placehold])
- [ ] Dispatch (Botão que envia uma requisição async e abilita uma notificação de progresso, enquanto um animação de load é exibida no botão)
- [ ] PopConfirm (um dialog com uma mensagem de confirmação, e botões, exibido de forma de popup)
- [ ] Transfer (duas listas de itens, e pode se mover de uma lista para outra)
- [ ] Empty (um componente que é exibido quando nenhuma informação/dados são encontrados)
- [ ] Result (visualiza o resultado)
